### ISSUE TITLE
about data prepare for training

### ISSUE THREAD

**Issue by zqaidwj1314** [k-han/SCNet#1]
Hi Kai Han,
Thanks for sharing the code. I am trying to train the model using the code you provided, but it seems that some file is missing.
Is 'PF-PASCAL-RP-500.mat' the region proposals you extracted on the PF-PASCAL dataset beforehand? Could you please give more details to prepare the data for training?
Thanks!

**Comment by 77QIQI** [comment]
@zqaidwj1314 @k-han 
Did you solve it? I cannot run RP successfully and i guess the PF-PASCAL-RP-500 is saved by RP algorithm. May you share the .mat in Github or share the method of another proposal method? Thank you in advance.

**Comment by k-han** [comment]
Hi @zqaidwj1314 @77QIQI ,

We have put the data preparation code in PF-PASCAL-code folder. The code is for training data preparation. For testing data, you may adjust a little bit following the comments in `generateGTpairs.m`. 

Best,
Kai

**Comment by 77QIQI** [comment]
@k-han  Thanks very much for your sharing. But I didn't find SS.m/RP.m in the PF-PASCAL-code and SCNet-baseline folders. Do I miss them or need to write by myself? Thank you again.
